name: Build and Release

permissions:
  contents: write  # Grants permission to create releases

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    if: (github.event_name == 'push' && github.ref == 'refs/heads/main') || github.event_name == 'pull_request'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt update && sudo apt install -y build-essential libssl-dev libboost-all-dev

      - name: Compile the project
        run: |
          make
          g++ sdhash-src/sdhash.o sdhash-src/sdhash_threads.o libsdbf.a -o JC-sdhash -fopenmp \
            -L. -L./external/stage/lib -L/usr/lib/x86_64-linux-gnu \
            -lboost_system -lboost_filesystem -lboost_program_options -lc -lm -lcrypto -lboost_thread -lpthread
          mv JC-sdhash SDhash
          ls -lah

      - name: Create release artifact
        uses: actions/upload-artifact@v4
        with:
          name: SDhash-binary
          path: ./SDhash

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: SDhash-binary
          path: .

      - name: Verify artifact
        run: ls -lah  # Debug step to confirm SDhash exists

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./SDhash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
