name: Build and Release

on:
  push:
    branches:
      - main  # Runs when pushing to main branch
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt update && sudo apt install -y build-essential libssl-dev libboost-all-dev

      - name: Compile the project
        run: |
          make  # Build the project
          g++ sdhash-src/sdhash.o sdhash-src/sdhash_threads.o libsdbf.a -o JC-sdhash -fopenmp \
            -L. -L./external/stage/lib -L/usr/lib/x86_64-linux-gnu \
            -lboost_system -lboost_filesystem -lboost_program_options -lc -lm -lcrypto -lboost_thread -lpthread
          mv JC-sdhash SDhash  # Rename the output binary
          ls -lah  # List files to verify the build


      - name: Create release artifact
        uses: actions/upload-artifact@v4
        with:
          name: SDhash-binary
          path: ./SDhash  # Path to the renamed binary

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: SDhash-binary
          path: .

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./SDhash  # Uploads the renamed binary
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
